import { useRef } from "react";
import type { ClaimData } from "@/lib/claim-data";
import { useAudit } from "@/contexts/AuditContext";
import { isDoubleBlindRequired } from "@/lib/claim-data";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { FileBarChart, Printer, ShieldCheck, Flag, AlertTriangle, Lock } from "lucide-react";

const ComplianceReportModal = () => {
  const { claims, verifiedCount, sessionHash } = useAudit();
  const printRef = useRef<HTMLDivElement>(null);

  const allClaims = Object.values(claims);
  const verifiedClaims = allClaims.filter(c => c.status === "verified");
  const flaggedClaims = allClaims.filter(c => c.status === "flagged");
  const pendingClaims = allClaims.filter(c => c.status === "pending" || c.status === "awaiting_second");

  const handlePrint = () => {
    const content = printRef.current;
    if (!content) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html>
      <head>
        <title>Bio-Trial Auditor — Regulatory Report</title>
        <style>
          body { font-family: 'Inter', sans-serif; color: #1A2B3C; padding: 40px; max-width: 800px; margin: 0 auto; }
          h1 { font-size: 20px; border-bottom: 2px solid #1A2B3C; padding-bottom: 8px; }
          h2 { font-size: 15px; margin-top: 24px; color: #1A2B3C; }
          .meta { font-family: monospace; font-size: 11px; color: #666; margin: 4px 0; }
          table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 12px; }
          th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; }
          th { background: #1A2B3C; color: white; font-size: 11px; text-transform: uppercase; }
          .verified { color: #2D9E5B; font-weight: 600; }
          .flagged { color: #DC2626; font-weight: 600; }
          .pending { color: #FFB400; font-weight: 600; }
          .hash { font-family: monospace; font-size: 10px; color: #999; word-break: break-all; }
          .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 10px; color: #999; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>${content.innerHTML}
        <div class="footer">
          <p>Generated by Bio-Trial Auditor v1.0 • ${new Date().toISOString()}</p>
          <p class="hash">Session Integrity Hash: ${sessionHash}</p>
          <p>This document is generated for 21 CFR Part 11 compliance demonstration purposes.</p>
        </div>
      </body>
      </html>
    `);
    win.document.close();
    win.print();
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="gap-1.5 text-xs">
          <FileBarChart className="h-3.5 w-3.5" />
          Generate Report
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-3xl max-h-[85vh] overflow-hidden flex flex-col">
        <DialogHeader className="flex-row items-center justify-between pr-8">
          <DialogTitle className="text-base flex items-center gap-2">
            <FileBarChart className="h-4 w-4" />
            Regulatory Compliance Report
          </DialogTitle>
          <Button variant="outline" size="sm" className="gap-1.5 text-xs" onClick={handlePrint}>
            <Printer className="h-3 w-3" />
            Print
          </Button>
        </DialogHeader>

        <div className="flex-1 overflow-auto pr-2" ref={printRef}>
          {/* Report Header */}
          <div className="mb-6">
            <h1 style={{ fontSize: 18, fontWeight: 700, marginBottom: 4 }}>
              Bio-Trial Auditor — Chain of Trust Report
            </h1>
            <p className="text-xs text-muted-foreground font-data">
              CSR-2026-0042 • Phase III Clinical Study Report
            </p>
            <p className="text-xs text-muted-foreground font-data">
              Generated: {new Date().toLocaleString()}
            </p>
          </div>

          {/* Summary stats */}
          <div className="grid grid-cols-3 gap-3 mb-6">
            <StatCard
              label="Verified"
              count={verifiedClaims.length}
              total={allClaims.length}
              icon={<ShieldCheck className="h-4 w-4 text-compliance" />}
              color="compliance"
            />
            <StatCard
              label="Flagged"
              count={flaggedClaims.length}
              total={allClaims.length}
              icon={<Flag className="h-4 w-4 text-destructive" />}
              color="destructive"
            />
            <StatCard
              label="Pending"
              count={pendingClaims.length}
              total={allClaims.length}
              icon={<AlertTriangle className="h-4 w-4 text-amber-accent" />}
              color="amber"
            />
          </div>

          <Separator className="my-4" />

          {/* Verified Claims Table */}
          {verifiedClaims.length > 0 && (
            <div className="mb-6">
              <h2 className="text-sm font-semibold mb-3 flex items-center gap-1.5">
                <ShieldCheck className="h-4 w-4 text-compliance" />
                Verified Claims ({verifiedClaims.length})
              </h2>
              <ClaimTable claims={verifiedClaims} statusLabel="Verified" />
            </div>
          )}

          {/* Flagged Claims Table */}
          {flaggedClaims.length > 0 && (
            <div className="mb-6">
              <h2 className="text-sm font-semibold mb-3 flex items-center gap-1.5">
                <Flag className="h-4 w-4 text-destructive" />
                Flagged Claims ({flaggedClaims.length})
              </h2>
              <ClaimTable claims={flaggedClaims} statusLabel="Flagged" />
            </div>
          )}

          {/* Pending */}
          {pendingClaims.length > 0 && (
            <div className="mb-6">
              <h2 className="text-sm font-semibold mb-3 flex items-center gap-1.5">
                <AlertTriangle className="h-4 w-4 text-amber-accent" />
                Pending Review ({pendingClaims.length})
              </h2>
              <ClaimTable claims={pendingClaims} statusLabel="Pending" />
            </div>
          )}

          {/* Session integrity */}
          <Separator className="my-4" />
          <div className="flex items-center gap-2 mb-2">
            <Lock className="h-3.5 w-3.5 text-muted-foreground" />
            <span className="text-xs font-semibold text-foreground">Session Integrity</span>
          </div>
          <p className="font-data text-[10px] text-muted-foreground break-all">
            SHA-256: {sessionHash}
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
};

function StatCard({ label, count, total, icon, color }: {
  label: string; count: number; total: number;
  icon: React.ReactNode; color: string;
}) {
  return (
    <div className="rounded-lg border bg-card p-3 text-center">
      <div className="flex items-center justify-center gap-1.5 mb-1">{icon}</div>
      <p className="text-lg font-bold text-foreground">{count}</p>
      <p className="text-[10px] text-muted-foreground">{label} of {total}</p>
    </div>
  );
}

function ClaimTable({ claims, statusLabel }: { claims: ClaimData[]; statusLabel: string }) {
  return (
    <div className="rounded-md border overflow-hidden">
      <table className="w-full text-xs">
        <thead>
          <tr className="bg-primary text-primary-foreground">
            <th className="px-3 py-2 text-left font-medium text-[10px] uppercase tracking-wider">Claim</th>
            <th className="px-3 py-2 text-left font-medium text-[10px] uppercase tracking-wider">Value</th>
            <th className="px-3 py-2 text-left font-medium text-[10px] uppercase tracking-wider">Section</th>
            <th className="px-3 py-2 text-left font-medium text-[10px] uppercase tracking-wider">Source</th>
            <th className="px-3 py-2 text-left font-medium text-[10px] uppercase tracking-wider">Tier</th>
            <th className="px-3 py-2 text-center font-medium text-[10px] uppercase tracking-wider">Confidence</th>
          </tr>
        </thead>
        <tbody>
          {claims.map((claim, i) => (
            <tr key={claim.id} className={i % 2 === 0 ? "bg-card" : "bg-muted/30"}>
              <td className="px-3 py-2 font-data">{claim.id.toUpperCase()}</td>
              <td className="px-3 py-2 font-data font-semibold">{claim.value}</td>
              <td className="px-3 py-2">{claim.section}</td>
              <td className="px-3 py-2 font-data text-[10px]">{claim.sourceRef}</td>
              <td className="px-3 py-2 text-center">
                <Badge variant="outline" className={`text-[9px] ${
                  claim.tier === 3 ? "border-destructive/40 text-destructive" : "border-muted-foreground/40"
                }`}>
                  T{claim.tier}
                </Badge>
              </td>
              <td className="px-3 py-2 text-center font-data">{claim.confidence}%</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default ComplianceReportModal;
